# Introduction

This web book is built around Malliavin Calculus and the Clark-Ocone formula. After many months, I figured the main problem with learning the topic is the emphasis on mathematical rigor over pedagogical clarity. The lack of real-life applications or practical examples in every source I consulted is also deeply frustrating.

So, I will start with developing what Malliavin calculus was meant to address. I will approach it in an indirect, meandering way. After documenting enough situations were a problem exists, the need for a solution will generate a "vacuum" of sorts. Following that, again indirectly, I'll lay the foundation step by step. Finally, the vacuum will be filled.

I chose to use Quarto because the source code and their results will be available. It helps when you see a piece of math and you relate that math to source code instructions.

As mentioned, pedagogical clarity is the guiding factor. I'll disregard proofs if I don't see them important. Shortcuts will be taken liberally. Some pieces will lead nowhere, and just be there to round up a concept, or even be red herrings. I may even admit when I'm ignorant about something and leave it like that.

Finally, I'm not a mathematician, a statistician or an economist. I'm just an Engineer trying to understand an obscure topic, mainly through a conversation with myself.
