# Introducción

Este ensayo trata sobre el Cálculo Malliavin y la fórmula de Clark-Ocone. Tras meses de estudio y frustración, concluí que el principal obstáculo para entender el tópico es el énfasis en el rigor matemático de las fuentes consultadas, por sobre la claridad pedagógica. Mi esperanza es conectar estos extremos, asumiendo conocimientos básicos de análisis matemático, álgebra, y probabilidad y estadística.

Voy a empezar desarrollando qué intenta lograr el Calculo Malliavin. Me aproximaré en forma indirecta, meandrosa. Luego de documentar situaciones donde existe un problema, la necesidad de una solución generará una especie de "vacío". Luego, también indirectamente, pondré las fundaciones paso a paso. Finalmente, el vacío sera llenado.

Elegí Quarto porque el código fuente y sus resultados estarán disponibles. Ayuda mucho ver una pieza de matemáticas y conectarla con instrucciones de código fuente.

Como dije anteriormente, la claridad pedagógica es el factor primordial. No voy a escribir demostraciones si no pienso que sean importantes. Tomaré atajos con impunidad. Algunas partes tal vez no lleven a ningún lado y solo estén ahí para redondear un concepto. Incluso puede que me declare ignorante sobre un tema y lo deje ahí.

La verdad es que no soy un profesional de las matemáticas, estadísticas o economía. Simplemente estoy tratando de entender un tópico muy árido y oscuro.

Y, ahora, es el momento de empezar.

------------------------------------------------------------------------
